In [1]:
import pandas as pd
books = pd.read_csv("books_with_categories.csv")

In [3]:
from transformers import pipeline
classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=None)
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.00852869637310505},
  {'label': 'neutral', 'score': 0.005764591973274946},
  {'label': 'anger', 'score': 0.004419790115207434},
  {'label': 'sadness', 'score': 0.002092393347993493},
  {'label': 'disgust', 'score': 0.001611992483958602},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [4]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [5]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548402309417725},
  {'label': 'neutral', 'score': 0.16985242068767548},
  {'label': 'sadness', 'score': 0.11640933901071548},
  {'label': 'surprise', 'score': 0.02070067822933197},
  {'label': 'disgust', 'score': 0.01910070888698101},
  {'label': 'joy', 'score': 0.015161458402872086},
  {'label': 'anger', 'score': 0.003935149405151606}]]

In [6]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.1403859555721283},
  {'label': 'fear', 'score': 0.0681624561548233},
  {'label': 'joy', 'score': 0.0479426272213459},
  {'label': 'anger', 'score': 0.009156373329460621},
  {'label': 'disgust', 'score': 0.002628481248393655},
  {'label': 'sadness', 'score': 0.0021221633069217205}],
 [{'label': 'neutral', 'score': 0.44937026500701904},
  {'label': 'disgust', 'score': 0.2735912799835205},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362754970788956},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697019651532173},
  {'label': 'fear', 'score': 0.006879047490656376}],
 [{'label': 'neutral', 'score': 0.6462159156799316},
  {'label': 'sadness', 'score': 0.24273331463336945},
  {'label': 'disgust', 'score': 0.04342269152402878},
  {'label': 'surprise', 'score': 0.02830054797232151},
  {'label': 'joy', 'score': 0.01421149168163538},
  {'label': 'fear', 'score': 0.01408409047871828},
  {'label': 'anger', 'score': 0.011031895875930786}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.032190803438425064},
  {'label': 'neutral', 'score': 0.012808690778911114},
  {'label': 'sadness', 'score': 0.008756859228014946},
  {'label': 'surprise', 'score': 0.008597897365689278},
  {'label': 'disgust', 'score': 0.008431811816990376},
  {'label': 'joy', 'score': 0.001045582932420075}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.01510414108633995},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393990781158209},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338779289275408}],
 [{'label': 'joy', 'score': 0.9327980279922485},
  {'label': 'disgust', 'score': 0.037717122584581375},
  {'label': 'neutral', 'score': 0.015891825780272484},
  {'label': 'sadness', 'score': 0.006444509141147137},
  {'label': 'anger', 'score': 0.005024970043450594},
  {'label': 'surprise', 'score': 0.0015812042402103543},
  {'label': 'fear', 'score': 0.0005423062248155475}],
 [{'label': 'joy', 'score': 0.6528708338737488},
  {'label': 'neutral', 'score': 0.2542746961116791},
  {'label': 'surprise', 'score': 0.06808288395404816},
  {'label': 'sadness', 'score': 0.009908987209200859},
  {'label': 'disgust', 'score': 0.0065122200176119804},
  {'label': 'anger', 'score': 0.004821304697543383},
  {'label': 'fear', 'score': 0.0035290142986923456}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400670021772385},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136281996965408},
  {'label': 'joy', 'score': 0.04056443274021149}]]

In [7]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [8]:
sentences

['A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives',
 ' John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers',
 ' It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up',
 ' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist',
 ' He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption',
 ' Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer',
 ' At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike',
 '']

In [9]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [10]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296019792556763},
 {'label': 'neutral', 'score': 0.1403859555721283},
 {'label': 'fear', 'score': 0.0681624561548233},
 {'label': 'joy', 'score': 0.0479426272213459},
 {'label': 'anger', 'score': 0.009156373329460621},
 {'label': 'disgust', 'score': 0.002628481248393655},
 {'label': 'sadness', 'score': 0.0021221633069217205}]

In [11]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [12]:
predictions[3]

[{'label': 'fear', 'score': 0.9281682968139648},
 {'label': 'anger', 'score': 0.032190803438425064},
 {'label': 'neutral', 'score': 0.012808690778911114},
 {'label': 'sadness', 'score': 0.008756859228014946},
 {'label': 'surprise', 'score': 0.008597897365689278},
 {'label': 'disgust', 'score': 0.008431811816990376},
 {'label': 'joy', 'score': 0.001045582932420075}]

In [13]:
predictions

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.1403859555721283},
  {'label': 'fear', 'score': 0.0681624561548233},
  {'label': 'joy', 'score': 0.0479426272213459},
  {'label': 'anger', 'score': 0.009156373329460621},
  {'label': 'disgust', 'score': 0.002628481248393655},
  {'label': 'sadness', 'score': 0.0021221633069217205}],
 [{'label': 'neutral', 'score': 0.44937026500701904},
  {'label': 'disgust', 'score': 0.2735912799835205},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362754970788956},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697019651532173},
  {'label': 'fear', 'score': 0.006879047490656376}],
 [{'label': 'neutral', 'score': 0.6462159156799316},
  {'label': 'sadness', 'score': 0.24273331463336945},
  {'label': 'disgust', 'score': 0.04342269152402878},
  {'label': 'surprise', 'score': 0.02830054797232151},
  {'label': 'joy', 'score': 0.01421149168163538},
  {'label': 'fear', 'score': 0.01408409047871828},
  {'label': 'anger', 'score': 0.011031895875930786}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.032190803438425064},
  {'label': 'neutral', 'score': 0.012808690778911114},
  {'label': 'sadness', 'score': 0.008756859228014946},
  {'label': 'surprise', 'score': 0.008597897365689278},
  {'label': 'disgust', 'score': 0.008431811816990376},
  {'label': 'joy', 'score': 0.001045582932420075}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.01510414108633995},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393990781158209},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338779289275408}],
 [{'label': 'joy', 'score': 0.9327980279922485},
  {'label': 'disgust', 'score': 0.037717122584581375},
  {'label': 'neutral', 'score': 0.015891825780272484},
  {'label': 'sadness', 'score': 0.006444509141147137},
  {'label': 'anger', 'score': 0.005024970043450594},
  {'label': 'surprise', 'score': 0.0015812042402103543},
  {'label': 'fear', 'score': 0.0005423062248155475}],
 [{'label': 'joy', 'score': 0.6528708338737488},
  {'label': 'neutral', 'score': 0.2542746961116791},
  {'label': 'surprise', 'score': 0.06808288395404816},
  {'label': 'sadness', 'score': 0.009908987209200859},
  {'label': 'disgust', 'score': 0.0065122200176119804},
  {'label': 'anger', 'score': 0.004821304697543383},
  {'label': 'fear', 'score': 0.0035290142986923456}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400670021772385},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136281996965408},
  {'label': 'joy', 'score': 0.04056443274021149}]]

In [14]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156373329460621},
 {'label': 'disgust', 'score': 0.002628481248393655},
 {'label': 'fear', 'score': 0.0681624561548233},
 {'label': 'joy', 'score': 0.0479426272213459},
 {'label': 'neutral', 'score': 0.1403859555721283},
 {'label': 'sadness', 'score': 0.0021221633069217205},
 {'label': 'surprise', 'score': 0.7296019792556763}]

In [15]:
import numpy as np
emotions_labels = ["anger","disgust", "fear", "joy", "sadness", "surprise", "neutral" ]
isbn = []

emotions_score = { label: [] for label in emotions_labels }

def  calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotions_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotions_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [17]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotions_labels:
        emotions_score[label].append(max_scores[label])

In [18]:
emotions_score

{'anger': [np.float64(0.0641336739063263),
  np.float64(0.6126193404197693),
  np.float64(0.0641336739063263),
  np.float64(0.3514839708805084),
  np.float64(0.08141250908374786),
  np.float64(0.23222461342811584),
  np.float64(0.5381841063499451),
  np.float64(0.0641336739063263),
  np.float64(0.3006698489189148),
  np.float64(0.0641336739063263)],
 'disgust': [np.float64(0.2735912799835205),
  np.float64(0.34828460216522217),
  np.float64(0.10400670021772385),
  np.float64(0.15072253346443176),
  np.float64(0.1844957172870636),
  np.float64(0.7271749973297119),
  np.float64(0.15585501492023468),
  np.float64(0.10400670021772385),
  np.float64(0.2794815003871918),
  np.float64(0.1779261827468872)],
 'fear': [np.float64(0.9281682968139648),
  np.float64(0.9425276517868042),
  np.float64(0.9723207950592041),
  np.float64(0.36070629954338074),
  np.float64(0.09504343569278717),
  np.float64(0.05136281996965408),
  np.float64(0.7474274635314941),
  np.float64(0.404497355222702),
  np.float64(0.9155242443084717),
  np.float64(0.05136281996965408)],
 'joy': [np.float64(0.9327980279922485),
  np.float64(0.7044222950935364),
  np.float64(0.7672383189201355),
  np.float64(0.2518812119960785),
  np.float64(0.04056443274021149),
  np.float64(0.043375737965106964),
  np.float64(0.8725652694702148),
  np.float64(0.04056443274021149),
  np.float64(0.04056443274021149),
  np.float64(0.04056443274021149)],
 'sadness': [np.float64(0.6462159156799316),
  np.float64(0.8879395127296448),
  np.float64(0.5494767427444458),
  np.float64(0.7326847910881042),
  np.float64(0.8843896985054016),
  np.float64(0.6213918924331665),
  np.float64(0.71219402551651),
  np.float64(0.5494767427444458),
  np.float64(0.8402892351150513),
  np.float64(0.8603723645210266)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.4758804738521576),
  np.float64(0.11169017851352692),
  np.float64(0.4080028831958771),
  np.float64(0.8202828764915466),
  np.float64(0.35446107387542725),
  np.float64(0.11169017851352692)],
 'neutral': [np.float64(0.7296019792556763),
  np.float64(0.2525458037853241),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.27190351486206055),
  np.float64(0.07876552641391754),
  np.float64(0.23448686301708221),
  np.float64(0.13561402261257172),
  np.float64(0.07876552641391754)]}

In [19]:
# from tqdm import tqdm
# for i in tqdm(range(len(books))):
#     isbn.append(books["isbn13"][i])
#     sentences = books["description"][i].split(".")
#     predictions = classifier(sentences)
#     max_scores = calculate_max_emotion_scores(predictions)
#     for label in emotions_labels:
#         emotions_score[label].append(max_scores[label])

from tqdm import tqdm
emotions_labels = ["anger","disgust", "fear", "joy", "sadness", "surprise", "neutral" ]
isbn = []

emotions_score = { label: [] for label in emotions_labels }
for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotions_labels:
        emotions_score[label].append(max_scores[label])

100%|██████████| 5197/5197 [2:08:54<00:00,  1.49s/it]

In [23]:
emotions_df = pd.DataFrame(emotions_score)
emotions_df["isbn13"] = isbn

In [24]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602,9780002005883
1,0.612619,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078766,9780006178736
3,0.351484,0.150723,0.360706,0.251881,0.732685,0.111690,0.078766,9780006280897
4,0.081413,0.184496,0.095043,0.040564,0.884390,0.475880,0.078766,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459269,0.759456,0.951104,0.368110,0.078766,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [25]:
books = pd.merge(books, emotions_df, on="isbn13")

In [26]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,simple_categories,predicted_categories_x,predicted_categories_y,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Fiction,NaN,NaN,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Fiction,Fiction,Fiction,0.612619,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Fiction,NaN,NaN,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,Nonfiction,Nonfiction,Nonfiction,0.351484,0.150723,0.360706,0.251881,0.732685,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,Nonfiction,Nonfiction,Nonfiction,0.081413,0.184496,0.095043,0.040564,0.884390,0.475880,0.078766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Fiction,Fiction,Fiction,0.148208,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Nonfiction,Nonfiction,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,Fiction,Fiction,Fiction,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,Nonfiction,NaN,NaN,0.064134,0.104007,0.459269,0.759456,0.951104,0.368110,0.078766
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,Nonfiction,NaN,NaN,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766

In [27]:
books.to_csv("books_with_emotions.csv", index=False)